In [ ]:
import numpy as np
import pandas as pd
import ast

# Veure que tensorflow i keras siguin les versions correctes (pip install --upgrade keras tensorflow)
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Conv1D
from keras.layers import MaxPooling1D
from sklearn.model_selection import train_test_split

: 

In [8]:
import numpy as np
import pandas as pd
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Conv1D
from keras.layers import MaxPooling1D
from sklearn.model_selection import train_test_split

ImportError: cannot import name 'keras' from 'tensorflow' (unknown location)

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Conv1D
from keras.layers import MaxPooling1D
from sklearn.model_selection import train_test_split

In [66]:
"""Funcions varies"""

def column_to_end(df, columna):
    # funció per moure una columna al final
    columnes = df.columns.tolist()
    index=df.columns.get_loc(columna)
    noves_columnes = columnes[:index] + columnes[index+1:] + columnes[index:index+1]  
    return noves_columnes

In [2]:
# multivariate data preparation
from numpy import array
from numpy import hstack
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
print(dataset)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [3]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
    # find the end of this pattern
        end_ix = i + n_steps
    # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
    # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [4]:
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(7, 3, 2) (7,)
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [17]:
len(X)

7

In [13]:
dataset[1:4,:-1]

array([[20, 25],
       [30, 35],
       [40, 45]])

In [23]:
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=1000, verbose=0)


In [24]:
# demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[205.66971]]


# EXEMPLE AMB GAZEDATA

In [71]:
data_1 = pd.read_csv('gazedata_csv')
data_2 = pd.read_csv('gazedata_2_csv')
data_1['class'] = 0
data_2['class'] = 1
df = pd.concat([data_1, data_2], ignore_index=True, sort=False)
df['gaze2d'] = df['gaze2d'].apply(ast.literal_eval)
df[['gaze2d_x','gaze2d_y']] = pd.DataFrame(df.gaze2d.tolist(), index= df.index)
vectors = ['gaze2d', 'gaze3d', 'eyeleft_gazeorigin', 'eyeleft_gazedirection', 'eyeright_gazeorigin', 'eyeright_gazedirection']
df.drop(vectors, axis=1, inplace=True); 
df = df[column_to_end(df, 'class')]

In [1]:
data = pd.read_csv('Data/gazedata_csv_definitiu/Guillem_with_level1.csv'); data

NameError: name 'pd' is not defined

In [73]:
df = df.to_numpy(); df

array([[1.19394053e+03, 3.74233246e+00, 3.55968571e+00, 4.17074495e-01,
        4.84910739e-01, 0.00000000e+00],
       [1.19394053e+03, 3.74233246e+00, 3.55968571e+00, 4.17074495e-01,
        4.84910739e-01, 0.00000000e+00],
       [8.05140000e-02, 3.71927524e+00, 3.31421900e+00, 5.66674991e-01,
        4.34058991e-01, 0.00000000e+00],
       ...,
       [2.77414394e+02, 4.57190371e+00, 4.87526131e+00, 4.45226328e-01,
        3.05139429e-01, 1.00000000e+00],
       [2.77434379e+02, 4.57960653e+00, 4.89377403e+00, 4.44405004e-01,
        2.98694104e-01, 1.00000000e+00],
       [2.77454466e+02, 4.57428408e+00, 4.90214491e+00, 4.44639026e-01,
        2.93898952e-01, 1.00000000e+00]])

In [ ]:
SVM I KNN
FER EL MAPA DE CALOR I CNN
MAPA DE CALOR ESTÀTIC I EN SEQUÈNCIA


In [44]:
n_steps = 60
# convert into input/output
X, y = split_sequences(df, n_steps)
print(X.shape, y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

(73947, 60, 3) (73947,)


In [48]:
n_features = X.shape[2]
# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])
# fit model
model.fit(X_train, y_train, epochs=2, verbose=0, validation_data=(X_test, y_test))

In [49]:
model.fit(X_train, y_train, epochs= 2, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/2
1849/1849 [==============================] - 5s 3ms/step - loss: 2.1061 - accuracy: 0.8781 - val_loss: 7.0324 - val_accuracy: 0.8571
Epoch 2/2
1849/1849 [==============================] - 5s 3ms/step - loss: 1.0962 - accuracy: 0.8580 - val_loss: 0.1395 - val_accuracy: 0.9940
